<main>
   <div class="page-container container defaultpage-about">
      <div class="default-page-about">
         <h3>İSTİFADƏÇİ RAZILAŞMASI</h3>
         <div class="page-defaultbout">
            <p><strong>1. Ümumi qaydalar</strong></p>
            <p><strong>1.1.</strong>&nbsp;Bu razılaşma&nbsp;<a href="https://estate.az">https://estate.az</a>&nbsp;Servisin İstifadəçiləri tərəfindən istifadə şərtlərini müəyyən edir.</p>
            <p><strong>1.2.</strong>&nbsp;Həmin İstifadəçi Razılaşmanın məqsədləri üçün aşağıda göstərilən terminlər və təyinlər aşağıdakı mənada tətbiq olunur:</p>
            <p><strong>1.2.1. Servis</strong>&nbsp;– İnternet şəbəkəsində&nbsp;<a href="https://estate.az">https://estate.az</a> ünvanında yerləşdirilmiş İnternet-resursu (sayt)</p>
            <p><strong>1.2.2. Administrasiya</strong>&nbsp;–&nbsp;Xidməti inzibatçılığını Azərbaycan Respublikasının qanunvericiliyinə uyğun olaraq yaradılmış (VÖEN 2006064072) şirkət həyat keçirir. İnternet resursuna aid bütün mülkiyyət hüquqları şirkətə aiddir.</p>
            <p><strong>1.2.3. İstifadəçi</strong>&nbsp;– razılaşma şərtlərini qəbul etmiş və Servis xidmətlərindən istifadə edən istənilən hüquq səlahiyyəti olan şəxsdir.</p>
            <p><strong>1.2.4. Şəxsi hesab</strong>&nbsp;– bu İstifadəçinin mühitinin İstifadəçi tərəfindən müəyyən edilmiş (yerləşdirilmiş) məlumatlar və qurmalar məcmusudur.</p>
            <p><strong>1.2.5. İstifadəçinin şəxsi informasiyası</strong>&nbsp;– İstifadəçi haqqında məlumatlardır və ya məlumatlar məcmusudur ki, İstifadəçi özü haqqında, İstifadəçinin şəxsi məlumatları, Servisdən istifadə prosesində Administrasiyaya avtomatik olaraq ötürülən informasiya, o cümlədən IP-ünvan, cookie-dən informasiya, İstifadəçinin brauzeri haqqında və İstifadəçi haqqında başqa informasiyalar daxil olmaqla, qeydiyyat vaxtı sərbəst və ya Servisdən istifadə prosesində təqdim edir.</p>
            <p><strong>1.2.6. İnformasiya</strong>&nbsp;– Servisdə İstifadəçi və ya Administrasiya tərəfindən yerləşdirilmiş istənilən informasiyadır.</p>
            <p><strong>1.2.7. Spam</strong>&nbsp;– alanlar tərəfindən kütləvi, icazə verilməyən və/və ya gözlənməyən reklam, informasiya, təşviqat və ya başqa xarakterli poçt və başqa göndərilmələrdir.</p>
            <p><strong>1.2.8. Əmlak</strong>&nbsp;– bu məhsul, işlər, xidmətlər, maddi-texniki resurslar, mülki və qeyri-mülki hüquqlardır.</p>
            <p><strong>1.2.9. Həmin Razılaşmanın Tərəfləri</strong>&nbsp;– Administrasiya və İstifadəçidir.</p>
            <p><strong>1.3.</strong>&nbsp;Həmin İstifadəçi Razılaşmasında istifadə olunan və "Terminlər və təyinlər" bəndində əksini tapmayan istənilən terminlər və anlayışlar, İstifadəçi Razılaşmasının mətnindən yaranan mənaya müvafiq olaraq izah ediləcəkdir. İstifadəçi Razılaşmasında istifadə edilən terminin və ya təyinin izah edilməsi barədə istənilən fikir ayrılıqlarının yaranması halında Administrasiya tərəfindən müəyyən edilən izah etmə tətbiq ediləcəkdir.</p>
            <p><strong>1.4.</strong>&nbsp;Servis xidmətlərindən və materiallarından istifadə edilmə qüvvədə olan qanunvericiliyin normaları, həmçinin də hazırkı Razılaşma ilə tənzimlənir.</p>
            <p><strong>1.5.</strong>&nbsp;Hazırkı Razılaşma ictimai ofertadır.</p>
            <p><strong>1.6.</strong>&nbsp;Servis xidmətlərindən istifadə edərək, İstifadəçi hazırkı Razılaşmaya qoşulur və onun Servis xidmətlərindən istifadə üzrə təlimatlarına riayət etmək şərtlərini və öhdəliklərini qəbul edir.</p>
            <p><strong>1.7.</strong>&nbsp;Şirkət adından Servisdən istifadə halında belə şirkət hazırkı Razılaşmanı və onun şərtlərini qəbul edir.</p>
            <p><strong>1.8.</strong>&nbsp;Administrasiya istənilən vaxt birtərəfli qaydada hazırkı Razılaşmanın şərtlərini dəyişdirmək hüququna malikdir.</p>
            <p><strong>1.9.</strong>&nbsp;İstifadəçinin hazırkı Razılaşmanın şərtləri ilə və ya ona daxil edilmiş dəyişikliklərlə razılaşmadığı halda o Servisə girişdən imtina etməli, Servisin xidmətlərindən istifadə etməsini dayandırmalıdır.</p>
            <p><strong>1.10.</strong>&nbsp;Bununla Administrasiya İstifadəçilərə Servisin xidmətlərindən istifadə etməklə elanların yerləşdirilməsi və axtarışı üzrə xidmətləri təklif edir.</p>
            <p><strong>1.11.</strong>&nbsp;Ayrı xidmətlərin verilməsi xüsusi qaydalarla və/və ya razılaşmalarla tənzimlənə bilər.</p>
            <p><strong>1.12.</strong>&nbsp;İstifadəçi o haqda müddəanı qəbul edir ki, Servisin bütün materialları və xidmətləri və ya onların istənilən hissəsi reklamla müşayiət oluna bilər. İstifadəçi onunla razıdır ki, Administrasiya hər hansı məsuliyyəti daşımır və belə reklamla əlaqədar hər hansı öhdəlikləri yoxdur.</p>
            <p><strong>1.13.</strong>&nbsp;Servisdə qeydiyyat könüllüdür. Servisdə qeydiyyat halında İstifadəçi Servisin əlavə xidmətlərinə daxil olur. Administrasiya İstifadəçidən onun qeydiyyat vaxtı göstərdiyi məlumatların təsdiqlənməsini və təsdiqləyici sənədləri istənilən vaxt tələb etmək hüququnu öz ayağında saxlayır.</p>
            <p><strong>1.14.</strong>&nbsp;İstifadəçi öz parolunu gizli saxlamağı öhdəsinə götürür. İstifadəçi öz elektron ünvanından və paroldan istifadə ilə hərəkətlərə, həmçinin də İstifadəçinin Şəxsi hesabında yerinə yetirilən hərəkətlərə görə məsuliyyət daşıyır. İstifadəçi Servis xidmətlərindən yalnız öz şəxsi elektron ünvandan və paroldan istifadə ilə istifadə etmək hüququna malikdir. Əgər İstifadəçidə onun Şəxsi hesabına icazəsiz daxil olma haqqında şübhələnməyə əsaslar varsa, İstifadəçi öz parolunu sərbəst dəyişməyi öhdəsinə götürür.</p>
            <p><strong>1.15.</strong>&nbsp;Administrasiya İstifadəçilər tərəfindən qeydiyyat və/və ya avtorizasiya zamanı verilən informasiyanın düzgünlüyünün yoxlanması üçün xüsusi texniki qərarlardan istifadə etməkdə haqlıdır.</p>
            <p><strong>1.16.</strong>&nbsp;Administrasiya zəmanət verə bilməz ki, İstifadəçi həqiqətən təqdim edildiyi kimidir, Servisdə qeydiyyat zamanı İstifadəçi tərəfindən verilmiş informasiya isə doğrudur.</p>
            <p><strong>1.17.</strong>&nbsp;İstifadəçiyə bunun üçün Servisdə mümkün olan bütün alətlərdən istifadə edərək mümkün kontragentlərlə ünsiyyət saxlamağa tövsiyə edilir.</p>
            <p><strong>1.18.</strong>&nbsp;Administrasiya öz şəxsi mülahizəsi üzrə İstifadəçinin hazırkı Razılaşmanın şərtlərini pozan xidmətlərinə girişi dayandırmaq hüququnu öz ayağında saxlayır.</p>
            <p><strong>1.19.</strong>&nbsp;İstifadəçi tərəfindən başqa şəxslərin hüquqlarının və ya qüvvədə olan qanunvericiliyin pozması halında, həmçinin başqa səbəblərdən öz istədiyi kimi, Servis İstifadəçinin girişini məhdudlaşdırmaq və ya dayandırmaq hüququna malikdir.</p>
            <p><strong>1.20.</strong>&nbsp;İstifadəçi, hansının ki, xidmətlərə girişi dayandırılmışdır, və ya hansının ki, məlumatları etibarsızdır, Administrasiyanın xüsusi icazəsi olmadan təkrar olaraq qeydiyyatdan keçmək hüququna malik deyildir. Belə İstifadəçi həmçinin Servisə və onun xidmətlərinə giriş üçün başqa İstifadəçinin qeydiyyat məlumatlarından istifadə etmək hüquqlarına malik deyildir.</p>
            <p><strong>2. Servisdən istifadə. Elanların yerləşdirilməsi</strong></p>
            <p><strong>2.1.</strong>&nbsp;Administrasiya xüsusi formanın doldurandan sonra bütün qeydiyyatdan keçmiş və qeydiyyatdan keçməmiş İstifadəçilərə Servisdə elanları yerləşdirmək hüququnu verir.</p>
            <p><strong>2.2.</strong>&nbsp;İstifadəçi qanunvericilik və ya beynəlxalq hüququn normaları pozulması kimi baxıla bilən hərəkətləri, o cümlədən intellektual mülkiyyət, müəlliflər və/və ya yanaşı hüquqlar sahəsində, həmçinin Servisin normal işinin pozulmasına gətirib çıxaran və ya gətirib çıxara biləcək istənilən hərəkətləri, təşəbbüs etməməyə razılaşır.</p>
            <p><strong>2.3.</strong>&nbsp;Əmlaklar barəsində bütün sazişlər İstifadəçilər arasında birbaşa bağlanılır. Servis Servisin vasitəsi ilə İstifadəçilər tərəfindən həyata keçirilən sazişlərin iştirakçı və/və ya vasitəçisi deyildir. Administrasiya belə sazişlərə nəzarət etmir və onlara görə məsuliyyət daşımır.</p>
            <p><strong>2.4.</strong>&nbsp;İstifadəçinin Servisdəki şərhləri və başqa qeydləri qanunvericiliyin tələbləri və əxlaqın hamı tərəfindən qəbul edilmiş normaları ilə münaqişəyə girməməlidir.</p>
            <p><strong>2.5.</strong>&nbsp;İstifadəçi o haqda xəbərdarlıq edilmişdir ki, Administrasiya onun tərəfindən xarici resurslara girişə və istifadəyə görə məsuliyyət daşımır, hansılara ki, dair istinadlar Servisdə ola bilər. Administrasiya elanların məzmununa, başqa resurslara istinadlar və elanların təsvirində göstərilmiş başqa informasiyaya görə məsuliyyət daşımır.</p>
            <p><strong>2.6.</strong>&nbsp;İstifadəçi tərəfindən verilmiş elanları, məlumatları və informasiyanı dərc etmək hüququnun Administrasiya tərəfindən alınması məqsədi ilə İstifadəçi Administrasiyaya hər yerdə qüvvədə olan, müddətsiz, qaytarılmaz, qeyri-müstəsna istifadə, yayılma, nəşr, yığım, işlənmə, nümayiş, surət çıxarma, təkrarlama hüququnu, məlumatların, təsvirlərin, şəkillərin, video və audio materialların, məlumat bazalarının, nəşrlərin, müəllif hüquqlarının və intellektual mülkiyyət hüquqlarının, həmçinin İstifadəçi tərəfindən bütün məlum olan və ya məlum olmayan informasiya daşıyıcılarında istənilən başqa informasiyanın yenidən hasili hüququnu verir. Yuxarı sadalanmış hüquqlar Administrasiyaya pulsuz verilir. İstifadəçi Servisin bütün İstifadəçilərinə özünün tərəfindən yerləşdirilmiş informasiyaya girişə hüquq verir. Əlavə olaraq İstifadəçi Servisdə onun tərəfindən yerləşdirilmiş materiallara istənilən intellektual mülkiyyət hüquqlarına malikdir.</p>
            <p><strong>2.7.</strong>&nbsp;İstifadəçi tərəfindən istənilən informasiyanın və məlumatların verilməsi ilə əlaqədar olaraq üçüncü şəxslərin hüquqlarının pozulmasına görə Servis məsuliyyət daşımır.</p>
            <p><strong>2.8.</strong>&nbsp;Servisin istifadəçisi Servisin təlimatlarına uyğun olaraq elanları yerləşdirməyi və Əmlak və onun satılması şərtləri haqqında etibarlı və tam informasiyanı verməyi öhdəsinə götürür. İstifadəçi elanda göstərilmiş Əmlak haqqında informasiyanı yoxlamalı və, səhv və ya natamam məlumatlar aşkar edildikdə, elandakı lazımlı məlumatları düzəltməli və ya tamamlamalıdır.</p>
            <p><strong>2.9.</strong>&nbsp;Əmlak ilə elanı yerləşdirərək, İstifadəçi təsdiq edir ki, o elanda göstərilmiş hərəkətlərin belə Mal barəsində həyata keçirmək hüququna malikdir.</p>
            <p><strong>2.10.</strong>&nbsp;İstifadəçi təsdiq edir ki, Servisdə elanlarda informasiyanın və məlumatların yerləşdirilməsinə, bütün lazımlı hüquqlara, lisenziyalara, icazələrə malikdir, bütün patentlər, ticarət markaları, ticarət sirləri, intellektual mülkiyyət hüquqları daxil olmaqla, və ya uyğun olan yazılı razılığa, lisenziyaya və ya üçüncü şəxslərin onların adlarından, təsvirlərdən və ya başqa obyektlərdən istifadə üçün icazəsinə malikdir.</p>
            <p><strong>2.11.</strong>&nbsp;Servis İstifadəçidən yerləşdirilmiş Əmlak haqqında əlavə məlumatı və/və ya İstifadəçi tərəfindən verilmiş məlumatları təsdiqləyən sənədləşməni tələb etmək hüququna malikdir. Servis belə sənədləşmənin və ya informasiyanın verilməsinə qədər nəşri saxlamaq hüququna malikdir.</p>
            <p><strong>2.12.</strong>&nbsp;İstifadəçi Servisdə ona istənilən aid olan Əmlakları, bu şərt ilə ki, bunun üçün xüsusi icazələr tələb olunmur, həmçinin istifadənin qüvvədə olan qaydalarına riayət etmə şərti ilə, satmaq hüququna malikdir.</p>
            <p><strong>2.13.</strong>&nbsp;Xidmətlərin yüksək keyfiyyətini dəstəkləmək üçün, Servis Servisdə İstifadəçinin aktiv elanlarının miqdarını məhdudlaşdırmaq, həmçinin Servisdə İstifadəçinin hərəkətlərini məhdudlaşdırmaq hüququnu öz ayağında saxlayır.</p>
            <p><strong>2.14.</strong>&nbsp;Elanda Əmlakın İstifadəçi tərəfindən göstərilmiş təsviri bu Əmlakın satışı şərtlərini təşkil edir.</p>
            <p><strong>2.15.</strong>&nbsp;Xidmətin elanda göstərilmiş göstərilməsi şərtləri və ya satış şərtləri və Əmlakın təsviri, həmçinin elanın başqa şərtləri, həm elanın yerləşdirilməsi vaxtı, həm də gələcəkdə qüvvədə olan qanunvericiliyə və hazırkı Razılaşmaya zidd olmamalıdır. Əgər elanın hər hansı şərti belə olur və ya etiraf edilir, hansı ki, qüvvədə olan qanunvericiliyə və ya hazırkı Razılaşmaya dəyişikliklərin daxil etməsi nəticəsində qanunvericiliyə və/və ya hazırkı Razılaşmaya uyğun deyil, belə şərtlər və ya belə elan İstifadəçi tərəfindən elə tamamlanmalı və ya dəyişdirilməlidir ki, istənilən uyğunsuzluqlar aradan qaldırılsın. Uyğun olan dəyişikliklərin daxil etməsinin qeyri-mümkünlüyü halında belə elan İstifadəçi tərəfindən silinməlidir. Hazırkı bənddə göstərilmiş hadisələrin yaranması vaxtı Administrasiya belə elanların redaktəsi və ya silinməsi üzrə hərəkətləri İstifadəçinin ilkin xəbərdarlığı olmadan həyata keçirmək hüququnu öz ayağında saxlayır.</p>
            <p><strong>2.16.</strong>&nbsp;Servisdə o elanlar qadağan edilmişdir ki, nəşri qüvvədə olan qanunvericiliyi pozur, əxlaqın hamı tərəfindən qəbul edilmiş normalarına ziddir, təhqiredicidir və ya yersizdir, həmçinin də üçüncü şəxslərin hüquqlarını pozur. İstifadəçi əmin olmalıdır ki, təklif qüvvədə olan qanunvericilik və hazırkı Razılaşmanın şərtlərini pozmur.</p>
            <p><strong>2.17.</strong>&nbsp;Pullu xidmətlərdən istifadə zəmanət vermir ki, elan hazırkı Razılaşmanın pozulması zamanı Administrasiya tərəfindən bloklanmayacaqdır. Elanların yerləşdirilməsi qaydalarının pozulması halında ödənmiş xidmətlərə görə pul vasitələri qaytarılmır.</p>
            <p><strong>2.18.</strong>&nbsp;Elanda özündə satış, istifadə haqqında təklifləri və ya mallar və xidmətlər haqqında başqa informasiyanı saxlayan internet-saytların səhifələrinə istinadları qoymaq qadağandır.</p>
            <p><strong>2.19.</strong>&nbsp;İstifadəçi verilən xidmətləri dəstəkləməməyi və haqqında informasiyanı yaymamağı öhdəsinə götürür:</p>
            <p><strong>2.19.1.</strong>&nbsp;başqa ticarət meydançaları, internet-hərracları və/və ya internet mağazaları tərəfindən;</p>
            <p><strong>2.19.2.</strong>&nbsp;Servisdə həmin və ya daha az ödənişlə təqdim edilmiş malları və xidmətləri təklif edən başqa xidmətlər tərəfindən;</p>
            <p><strong>2.19.3.</strong>&nbsp;Servisdə satışa qadağan edilmiş malları və xidmətləri təklif edən başqa xidmətlər tərəfindən.</p>
            <p><strong>2.20.</strong>&nbsp;İstifadəçi Administrasiyanın yazı icazəsi olmadan Servisə girişin alınması üçün avtomatik proqramlardan istifadə etməməyi öhdəsinə götürür. Elanları yerləşdirməyə icazə verən kompüter proqramlarından istifadə elanların yerləşdirilməsinin adi sırasını keçərək, Administrasiyanın yazılı icazəsi olmadığı halda, qadağandır.</p>
            <p><strong>2.21.</strong>&nbsp;Bundan başqa, İstifadəçi öhdəsinə götürür:</p>
            <p><strong>2.21.1.</strong>&nbsp;Servisin infrastrukturunu böyük yüklənməyə gətirib çıxara bilən heç bir hərəkətə təşəbbüs etməməyi;</p>
            <p><strong>2.21.2.</strong>&nbsp;Administrasiyanın ilkin yazılı icazəsi olmadan Servisdə olanı istənilən informasiyanı köçürməməyi, təkrar etməməyi, dəyişdirməməyi, yaymamağı və ictimaiyyətə təqdim etməməyi;</p>
            <p><strong>2.21.3.</strong>&nbsp;Servisə girişə mane olmaq və ya məhdudlaşdırmaq məqsədi ilə Servisin işinə mane olmamağı, həmçinin avtomatik sistemlərin və ya proseslərin hərəkətinə mane olmamağı;</p>
            <p><strong>2.22.</strong>&nbsp;İstifadəçi tərəfindən verilmiş məlumatlar və onun Servisdə hərəkətləri olmamalıdır:</p>
            <p><strong>2.22.1.</strong>&nbsp;yanlışlıq, qeyri-dəqiqlik və ya aldatma;</p>
            <p><strong>2.22.2.</strong>&nbsp;dələduzluğa, aldatmağa və ya etimaddan sui-istifadəyə imkan yaratma;</p>
            <p><strong>2.22.3.</strong>&nbsp;oğurluq və ya saxta əşyalarla sazişlərin bağlanmasına aparma;</p>
            <p><strong>2.22.4.</strong>&nbsp;üçüncü şəxsin mülkiyyətini pozmaq və ya onun ticarət sirrinə və ya onun şəxsi həyatına toxunulmazlıq hüququna qəsd etmə;</p>
            <p><strong>2.22.5.</strong>&nbsp;özündə kiminsə şərəfini, ləyaqətini və ya işgüzar reputasiyasını təhqir edən məlumatları saxlama;</p>
            <p><strong>2.22.6.</strong>&nbsp;özündə kimə qaşı olursa olsun böhtan və ya təhdidləri saxlama;</p>
            <p><strong>2.22.7.</strong>&nbsp;cinayətin törədilməsinə çağırma, həmçinin millətlərarası düşmənçiliyi qızışdırma;</p>
            <p><strong>2.22.8.</strong>&nbsp;imkan yaratmaq, dəstəkləmək və ya terror və ekstremist fəaliyyətə çağırmaq;</p>
            <p><strong>2.22.9.</strong>&nbsp;ədəbsizlik, və ya pornoqrafiya xarakterini daşımaq;</p>
            <p><strong>2.22.10.</strong>&nbsp;özündə kompüter viruslarını saxlamaq, həmçinin də başqa kompüter proqramları, xüsusi halda, ziyanın çəkilməsinə, səlahiyyətsiz müdaxiləyə, gizli ələ keçirməyə və ya istənilən sistemin məlumatlarının və ya sistemin özünün, və ya onun hissəsinin, və ya şəxsi informasiyanın və ya başqa məlumatların (Servisin məlumatları daxil olmaqla) mənimsənməsinə yönəldilmiş;</p>
            <p><strong>2.22.11.</strong>&nbsp;özündə reklam xarakterli materialları saxlamaq;</p>
            <p><strong>2.22.12.</strong>&nbsp;üçüncü şəxslərin intellektual hüquqlarını, vətəndaşın təsvirinə hüququnu və üçüncü şəxslərin başqa hüquqlarını pozmaq;</p>
            <p><strong>2.22.13.</strong>&nbsp;qüvvədə olan qanunvericiliyi başqa üsulla pozmaq.</p>
            <p><strong>2.23.</strong>&nbsp;İstifadəçiyə Servisdə elanları yerləşdirməyə, Servisdə xidmətlərdən istifadə etməklə sazişləri bağlamaq və ya icra etməyə qadağan edilir ki, Servis və/və ya İstifadəçisi tərəfindən qüvvədə olan qanunvericiliyin pozulmasına gətirib çıxara bilər.</p>
            <p><strong>2.24.</strong>&nbsp;Administrasiya Servisdə barəsində elan yerləşdirilmiş Əmlakı, belə Əmlak barəsində elan verilməsi zamanı İstifadəçi tərəfindən göstərilmiş fərqlənən üsulla, reklam etmək hüququna malikdir.</p>
            <p><strong>2.25.</strong>&nbsp;Administrasiya istənilən elanın Servisdən asılı və ya müstəqil səbəblərdən nümayiş müddətlərinin yerini dəyişdirmək, dayandırmaq, bitirmək və ya uzatmaq hüququna malikdir.</p>
            <p><strong>2.26.</strong>&nbsp;Administrasiya istənilən vaxt istənilən elanın nümayişini, hazırkı Razılaşmada söylənmiş qaydaları pozan səbəblərdən, həmçinin də başqa İstifadəçilərin hüquqlarını pozan və ya qüvvədə olan qanunvericiliyi pozan səbəblərdən, həmçinin başqa səbəblərdən, dayandırmaq hüququna malikdir.</p>
            <p><strong>2.27.</strong>&nbsp;Administrasiya elanları redaktə etmək, onları başqa rubrikalara keçirmək, həmçinin İstifadəçilərin elanları ilə istənilən başqa hərəkətləri etmək hüququna malikdir.</p>
            <p><strong>2.28.</strong>&nbsp;Administrasiya elanların yerləşdirilməsindən (nəşrindən) imtina etmək hüququna malikdir.</p>
            <p><strong>2.29.</strong>&nbsp;Elanın rəsmiləşdirilməsinə dair tələblərlə (Servisdə elanların yerləşdirilməsi qaydaları ilə) bu keçidə daxil olaraq tanış ola bilərsiniz.</p>
            <p><strong>2.30.</strong>&nbsp;İstifadəçi qüvvədə olan qanunvericiliyə əsasən elanların məzmununa görə tam və xüsusi məsuliyyəti daşıyır.</p>
            <p><strong>3. Pullu xidmətlər</strong></p>
            <p><strong>3.1.</strong>&nbsp;İstifadəçilər Servisdə pullu xidmətləri sifariş edə bilərlər.</p>
            <p><strong>3.2.</strong>&nbsp;Pullu xidmətlərin növləri:</p>
            <p><strong>3.2.1.</strong>&nbsp;Axtarışda irəli çək</p>
            <p><strong>3.2.2.</strong>&nbsp;VIP</p>
            <p><strong>3.2.3.</strong>&nbsp;Premium</p>
            <p><strong>3.2.4.</strong>&nbsp;Ödənişli elan</p>
            <p><strong>3.3.</strong>&nbsp;Xidmətlərə qiymətlər, həmçinin pullu xidmətlərin sifariş qaydası Servisin müvafiq səhifələrində göstərilmişdir.</p>
            <p><strong>3.4.</strong>&nbsp;Servisin xidmətlərini ödəmiş Servis İstifadəçisi vasitələrin qaytarılması xahişi ilə Administrasiyaya müraciət etmək hüququna malikdir. Pul vasitələrinin qaytarılmasında qaytarılma və ya imtina haqqında qərar birtərəfli qayda ilə Administrasiya tərəfindən qəbul edilir.</p>
            <p><strong>3.5.</strong>&nbsp;Administrasiya pul vasitələrinin İstifadəçiyə qaytarılmasında imtina etməkdə bu hallarda haqlıdır, əgər:</p>
            <p><strong>3.5.1.</strong>&nbsp;İstifadəçi hazırkı Razılaşmanın şərtlərini müntəzəm pozur.</p>
            <p><strong>3.5.2.</strong>&nbsp;Əgər xidmət aktivləşdirilmişdir, həmçinin hallarda, əgər elan moderasiyadan sonra silinmişdir.</p>
            <p><strong>3.5.3.</strong>&nbsp;İstifadəçi qadağan edilmiş mallar, xidmətlər və təkliflər haqqında elanı yerləşdirmişdir.</p>
            <p><strong>3.5.4.</strong>&nbsp;Ödəmə sistemində hər hansı nasazlıqların yaranması halında. Servis İstifadəçilərin vasitəsilə Servis xidmətlərini ödəyən ödəmə sistemlərinin işinə görə məsuliyyət daşımır. Pul vasitələrinin bu halda qaytarılması haqqında məsələ fərdi qaydada həll edilir.</p>
            <p><strong>3.5.5.</strong>&nbsp;Digər hallarda Administrasiyanın qərarı üzrə.</p>
            <p><strong>3.6.</strong>&nbsp;Pul vəsaitlərin qaytarılma qaydası Administrasiya və İstifadəçi arasında hər konkret hal üçün müəyyən edilir.</p>
            <p><strong>4. Kommunikasiya</strong></p>
            <p><strong>4.1.</strong>&nbsp;Administrasiya İstifadəçilərə onların tərəfindən göstərilmiş elektron poçt ünvanlarına və ya telefon nömrələrinə elektron məktubları və/və ya qısa xəbərləri (SMS mesajları) göndərmək hüququna malikdir. Servisin mesajları Servisdə dərc edilə bilər.</p>
            <p><strong>4.2.</strong>&nbsp;Əlavə olaraq İstifadəçi anlayır, qəbul edir və razılaşır ki, belə məktublarla və mesajlarla, lakin, məhdudlaşdırılmadan: başqa İstifadəçilərdən sazişin bağlanması üzrə təkliflər, təkliflər və başqa informasiya və/və ya reklam xarakterli mesajlar və başqa mesajlar ola bilər. İstifadəçi anlayır, qəbul edir və razılaşır ki, belə mesajlar və/və ya onların ayrı hissələri reklam xarakterinə malik ola bilər, həmçinin də özündə reklam, informasiya və başqa elanları saxlaya bilər.</p>
            <p><strong>4.3.</strong>&nbsp;Servisdə dərc edilmiş mesajlar onların dərc edildiyi anından İstifadəçiyə çatdırılmış hesab edilir.</p>
            <p><strong>4.4.</strong>&nbsp;Administrasiya başqa İstifadəçilər tərəfindən istifadəyə və/və ya Servisdə mesajların forma üzrə yerləşdirilmiş avtomatlaşdırılmış sistemlərlə (robotlarla) göndərilməsinə görə məsuliyyət daşımır.</p>
            <p><strong>4.5.</strong>&nbsp;Administrasiya başqa İstifadəçilər və/və ya robotları tərəfindən Servisin səhifələrində İstifadəçi tərəfindən yerləşdirilmiş telefon nömrələrindən və elektron ünvanlarından istifadəyə görə məsuliyyət daşımır.</p>
            <p><strong>4.6.</strong>&nbsp;İstifadəçi təsdiqləyir ki, Administrasiya İstifadəçilərə məktub və mesajları göndərmək məqsədləri üçün elektron poçt ünvanlarını və telefon nömrələrini üçüncü şəxslərə vermək hüququna malikdir.</p>
            <p><strong>4.7.</strong>&nbsp;İstifadəçinin Administrasiya və ya Servisin moderatorları ilə yazışması ünvanı Servisdə göstərilən elektron poçt qutusunun köməyi ilə həyata keçirilir.</p>
            <p><strong>4.8.</strong>&nbsp;İstifadəçiyə Servisdə moderatorların və Administrasiyanın hərəkətləri haqqında şərhlər, müzakirələr və başqa yazıları qoymaq qadağandır.</p>
            <p><strong>4.9.</strong>&nbsp;İstifadəçi müvafiq sorğunu göndərib öz telefon nömrəsinə və ya elektron ünvana mesajların alınmasından istənilən vaxt imtina edə bilər.</p>
            <p><strong>5. Proqram təminatı</strong></p>
            <p><strong>5.1.</strong>&nbsp;Administrasiya saytın yerləşdirildiyi domen adının, saytın özünün, mobil əlavələrin, həmçinin bütün Servis və Servisin bütün proqram təminatının xüsusi sahibkarıdır.</p>
            <p><strong>5.2.</strong>&nbsp;Proqram təminatının yükləməsi zamanı Administrasiya İstifadəçiyə proqram təminatından istifadə üçün, onun üçüncü şəxslərə verilməsi hüququ olmadan, şəxsi pulsuz adi lisenziyanı verir.</p>
            <p><strong>5.3.</strong>&nbsp;Servisin funksiyalarına əsasən belə lisenziya istisna olaraq İstifadəçiyə Servisin xidmətlərindən istifadə imkanının verilməsi və onlardan xeyirlərin alınması üçü n nəzərdə tutulmuşdur.</p>
            <p><strong>5.4.</strong>&nbsp;(Servisin) Administrasiyanın (o cümlədən proqram təminatının) intellektual mülkiyyəti obyektlərinin surətini çıxarılması, dəyişdirilməsi, paylaşması, satılması (realizasiya edilməsi), mübadilə edilməsi və ya tamamilə və ya hər hansı hissəsinin icarəyə verilməsi, həmçinin də Administrasiyanın yazılı icazəsi olmadan proqram təminatının mənbə kodunun "sındırılması" və ya alınmasına cəhd edilməsi qadağan edilir.</p>
            <p><strong>6. Məsuliyyətin məhdudlaşdırılması</strong></p>
            <p><strong>6.1.</strong>&nbsp;Servisdə İstifadəçi tərəfindən göstərilmiş Bütün informasiya (o cümlədən şəxsi məlumatlar), İstifadəçi tərəfindən onun Əmlakın satılması (realizasiyası) üçün yerləşdirilir.</p>
            <p><strong>6.2.</strong>&nbsp;İstifadəçi özü haqqında bu və ya digər informasiyanı ancaq öz maraqlarında, o cümlədən İstifadəçi ilə əlaqənin qurulmasının sadələşdirilməsi və/və ya İstifadəçinin eyniləşdirməsi üçün yerləşdirir.</p>
            <p><strong>6.3.</strong>&nbsp;Özü haqqında informasiyanı yerləşdirərək, İstifadəçi anlayır və onunla razılaşır ki, belə informasiya Servisdə açıq girişdə yerləşdirilir, yəni tanış olma üçün istənilən müştəriyə və ya Servisin İstifadəçilərinə mümkündür.</p>
            <p><strong>6.4.</strong>&nbsp;İstifadəçi informasiyanın belə yerləşdirilməsi ilə bağlı bütün riskləri anlayır və özünə qəbul edir, o cümlədən, daxil etməklə, amma məhdudlaşdırılmadan: spam - mesajların göndərilməsi üçün siyahılara elektron poçt ünvanının düşməsi riski, elektron poçt ünvanının müxtəlif növ dələduzlara düşməsi riski, telefon nömrəsinin SMS-spamerlərə və/və ya SMS-dələduzlara düşməsi riski və informasiyanın belə yerləşdirməsindən irəli gələn başqa risklər.</p>
            <p><strong>6.5.</strong>&nbsp;Servis Əmlak barəsində sazişlərin təşkilatçısı, vasitəçisi, alıcısı və ya satıcısı deyildir.</p>
            <p><strong>6.6.</strong>&nbsp;Servis Servisin İstifadəçiləri tərəfindən sazişlərin bağlanmasına və icrasına (həyata keçirilməsinə), sazişlərin bağlanması nəticəsində vurulmuş ziyana, itmiş xeyirlərə, gəlirlərə, maliyyə zərərlərinə və ya vasitəli, faktiki, kənar və ya cərimə zərərlərinə, həmçinin hər hansı şəxsin qanunsuz əməlləri nəticəsində, görə məsuliyyət daşımır.</p>
            <p><strong>6.7.</strong>&nbsp;Servisin xidmətlərindən istifadə edib, İstifadəçi onunla öz razılığını təsdiqləyir ki, o Servisdən məsuliyyəti öz üzərinə götürərək istifadə edir, Servisdə yerləşdirilmiş elanların istifadəsi ilə bağlı bütün riskləri daşıyır.</p>
            <p><strong>6.8.</strong>&nbsp;Servis İstifadəçilərə realizasiyası (satışı) və/və ya əldə edilməsi qanunla, hazırkı Razılaşma ilə və Servisdən istifadənin başqa qaydaları ilə icazə verilmiş Əmlaklar barəsində elanları yerləşdirmək imkanı verən alətdir.</p>
            <p><strong>6.9.</strong>&nbsp;Servis İstifadəçilər tərəfindən yerləşdirilmiş elanları həmişə yoxlamır, nəticədə, keyfiyyət, təhlükəsizlik, qanunilik və əmlakın onun təsvirinə uyğunluğu, həmçinin də satıcının əmlakı satmaq və alıcısının əldə etmək imkanı Xidmətin kontrolundan kənardadır.</p>
            <p><strong>6.10.</strong>&nbsp;Servis İstifadəçilər tərəfindən elanlarda yerləşdirilən informasiyanın etibarlılığına nəzarət edə bilmir.</p>
            <p><strong>6.11.</strong>&nbsp;Servis, onun Administrasiyası, rəhbərlik və əməkdaşlar, Servisdə yerləşdirilmiş elanların məzmununa, həmçinin onların etibarlılığına görə heç bir məsuliyyət daşımırlar.</p>
            <p><strong>6.12.</strong>&nbsp;Administrasiya, onun rəhbərliyi və əməkdaşlar, istənilən xəbərlərin (o cümlədən, İstifadəçilər tərəfindən poçt qutusuna və/və ya mobil telefona alınan), məzmununa görə, həmçinin də İstifadəçilərin əlaqə məlumatlarının başqa istifadəsinə görə, heç bir məsuliyyət daşımırlar.</p>
            <p><strong>6.13.</strong>&nbsp;İstifadəçi anlayır ki, Servisdə elanın yerləşdirilməsi faktı onun zəmanəti deyil ki, hər hansı Malın təklifi, satılması və/və ya əldə edilməsi həqiqidir və qanunidir. Sazişin həyata keçirilməsi haqqında qərarı İstifadəçi sərbəst olaraq qəbul edir.</p>
            <p><strong>6.14.</strong>&nbsp;Qanunvericiliklə icazə verilmiş dərəcədə, Servisin istənilən iddialar üzrə ümumi məsuliyyəti İstifadəçi tərəfindən Servisin xidmətlərindən istifadəsinə görə və ya (Servisin mülahizəsinə görə) bu xidmətlərin İstifadəçiyə təkrar verilməsi ilə ödənmiş məbləğ ilə məhdudlaşdırılır.</p>
            <p><strong>6.15.</strong>&nbsp;İstifadəçi razılaşır ki, İstifadəçinin və başqa İstifadəçilərin və/və ya Servisin müştəriləri arasındakı bütün mübahisələr (o cümlədən sazişlərin həyata keçirilməsi nəticəsində) İstifadəçi Administrasiyanı cəlb etmədən sərbəst həll edir.</p>
            <p><strong>6.16.</strong>&nbsp;Administrasiya Servisin xidmətlərinə üçüncü şəxslərin Administrasiyanın razılığı (icazəsi) və/və ya məlumatı olmadan həyata keçirilmiş istənilən girişinə və/və ya İstifadəçilər haqqında istənilən informasiyaya görə (o cümlədən şəxsi məlumatlar), məsuliyyət daşımır.</p>
            <p><strong>6.17.</strong>&nbsp;İstifadəçi onunla razıdır ki, Administrasiya İstifadəçi qarşısında Servisin istənilən məzmunu ilə bağlı və/və ya İstifadəçi tərəfindən həyata keçirilmiş sazişlər nəticəsində istənilən mümkün və ya yaranmış itkilərlə və ya zərərlərlə əlaqədar, müəllif hüquqlarının qeydiyyatı ilə və belə qeydiyyat haqqında məlumatlarla, Servisdə mümkün olan mallarla və ya xidmətlərlə və ya İstifadəçinin Servisdə yerləşdirilmiş informasiyadan istifadə edərək daxil olduğu başqa əlaqələri ilə, məsuliyyət daşımır və birbaşa və ya dolayı öhdəliklərə malik deyildir.</p>
            <p><strong>6.18.</strong>&nbsp;Administrasiya Servisə ötürülə bilən və ya Servis vasitəsilə üçüncü şəxslər tərəfindən çatdırıla bilən istənilən proqram nasazlıqları, sınıqlar və başqa texniki və proqram nasazlıqlarına görə, həmçinin səhvlərə, proqram viruslarına, və s. görə məsuliyyət daşımır.</p>
            <p><strong>6.19.</strong>&nbsp;İstifadəçi yalnız qüvvədə olan qanunvericiliyə və hazırkı Razılaşmaya uyğun olaraq hərəkət etməyi, həmçinin qanunvericiliyə uyğun olaraq Servisdə və Servisin xidmətlərindən istifadə vaxtı şəxsi hərəkətlərinə və fəaliyyətsizliyinə görə tam məsuliyyət daşımağı öhdəsinə götürür.</p>
            <p><strong>6.20.</strong>&nbsp;Servisin İstifadəçisinin başqa İstifadəçisi tərəfindən hüquqlarının pozulduğu halda (intellektual mülkiyyət obyektinin qanunsuz istifadəsi və sair), İstifadəçi, kimin ki hüquqlar pozulmuşdur, müvafiq şikayət ilə Administrasiyaya və ya moderatorlara müraciət edə bilər. Administrasiya şikayətə baxmağı və, onun əsaslı olduğu halda, İstifadəçinin hüquqlarının pozulmasının dayandırılması tədbirlər görməyi öhdəsinə götürür.</p>
            <p><strong>7. İstifadə qaydalarının hərəkət müddəti</strong></p>
            <p><strong>7.1.</strong>&nbsp;Hazırkı razılaşma İstifadəçi tərəfindən Servisin xidmətlərindən istifadəsinin başlanğıcı anından qüvvəyə minir, Servisdə İstifadəçinin qeydiyyatı və ya elanın yerləşdirilməsi faktından asılı olmayaraq, və müddətsiz qüvvədədir.</p>
            <p><strong>7.2.</strong>&nbsp;İstifadəçi istənilən vaxt özünün Servisin xidmətlərindən istifadə hüququnu dayandırmaq hüququna malikdir. Bundan sonra İstifadəçi yeni Elanları yerləşdirmək hüququna malik deyildir.</p>
            <p><strong>7.3.</strong>&nbsp;Servis şəxsi mülahizə üzrə İstifadəçinin girişini dayandırmaq hüququna malikdir. Xidmətlərə girişi dayandırılan və ya məlumatları həqiqi olmayan İstifadəçi Administrasiyanın xüsusi icazəsi olmadan təkrar qeydiyyatdan keçmək hüquqlarına malik deyil, həmçinin belə İstifadəçi Servisə giriş üçün başqa İstifadəçinin qeydiyyat məlumatlarından istifadə etmək hüquqlarına malik deyildir.</p>
            <p><strong>8. Digər şərtlər</strong></p>
            <p><strong>8.1.</strong>&nbsp;Mübahisələrin yarandığı halda hazırkı Razılaşmanın tərəfləri onları danışıqlar yolu ilə həll etməyi öhdəsinə götürürlər. Hazırkı Razılaşmanın və Servis xidmətlərinin verilməsinin icrası zamanı yaranan mübahisələr qüvvədə olan qanunvericiliyə uyğun olaraq həll edilməlidir.</p>
            <p><strong>8.2.</strong>&nbsp;Bütün mübahisələrə dair Azərbaycanın qanunvericiliyi tətbiq edilir.</p>
            <p><strong>8.3.</strong>&nbsp;Servis birtərəfli qaydada və İstifadəçilərə bildirmədən hazırkı Razılaşmanı dəyişdirmək hüququna malikdir. Razılaşmanın yeni redaksiyası Servisdə dərc edilməsi tarixindən qüvvəyə minir.</p>
            <p><strong>8.4.</strong>&nbsp;Razılaşmada heç nə İstifadəçi və Administrasiya arasında agent münasibətlərinin, Yoldaşlığın münasibətlərinin, birgə fəaliyyət üzrə münasibətlər, şəxsi işəgötürmənin münasibətlərinin, və ya Razılaşma ilə birbaşa nəzərdə tutulmamış hər hansı bir başqa münasibətlərin müəyyən edilməsi kimi anlaşıla və izah edilə bilməz.</p>
            <p><strong>8.5.</strong>&nbsp;Məhkəmə tərəfindən Razılaşmanın hər hansı müddəasının etibarsız və ya məcburi icraya aid olmayan kimi tanınması Razılaşmanın başqa müddəalarının etibarsız olması ilə nəticələnmir.</p>
            <p><strong>8.6.</strong>&nbsp;Razılaşmanın müddəalarının İstifadəçilərindən hər hansı biri tərəfindən pozulması halında Administrasiya tərəfindən fəaliyyətsizlik daha sonra Administrasiyanı öz maraqlarının və hüquqlarının müdafiəsinə uyğun olan hərəkətləri təşəbbüs etmək hüququndan məhrum etmir.</p>
            <p><strong>8.7.</strong>&nbsp;Hazırkı Razılaşma ilə nəzərdə tutulmamış bütün başqa şərtlər və şəraitlər, ayrı fərdi qaydada tənzimlənir.</p>
            <p><strong>İstifadəçi təsdiqləyir ki, hazırkı Razılaşmanın bütün bəndləri ilə tanış edilmişdir və onları sözsüz tam həcmdə qəbul edir.</strong></p>
            <p>Əlavələr:</p>
            <p><strong>1.</strong>&nbsp;Əlavə № 1</p>
            <p><a href="https://estate.az">https://estate.az</a> <strong>İstifadəçi Razılaşmasına dair Əlavə № 1</strong></p>
            <p><strong>1. Məxfilik siyasəti</strong></p>
            <p><strong>1.1.</strong>&nbsp;Hazırkı məxfilik Siyasəti&nbsp;<a href="https://estate.az">https://estate.az</a>&nbsp;Servisin İstifadəçi Razılaşmasının ayrılmaz hissəsidir.</p>
            <p><strong>1.2.</strong>&nbsp;Hazırkı məxfilik Siyasəti İstifadəçinin şəxsi məlumatlarının alması, saxlaması, işlənməsi, istifadəsi, açılması və müdafiəsi qaydasını müəyyən edir.</p>
            <p><strong>1.3.</strong>&nbsp;İstifadəçilərin şəxsi məlumat bazası Administrasiyanın ünvanı üzrə yerləşir.</p>
            <p><strong>1.4.</strong>&nbsp;Şəxsi məlumatlar Bazasının sərəncamçısı Administrasiyadır – (VÖEN 2006064072 məxsus) şirkətidir.</p>
            <p><strong>1.5.</strong>&nbsp;Elanın dərc edilməsi üçün formanı dolduran zaman və ya Servisdə İstifadəçinin qeydiyyatı zamanı, və ya göndərmələrə abunə yazılma zamanı, həmçinin də Servisdən istifadənin başqa hallarında, İstifadəçi Administrasiyaya məlumatları və şəxsi məlumatları verir. Məlumatın toplanması həmçinin Servisin İstifadəçilərinin sorğularının keçirilməsi yolu ilə həyata keçirilə bilər. İstifadəçilərin sorğularında iştirak İstifadəçilər icazəsi ilə həyata keçirilir.</p>
            <p><strong>1.6.</strong>&nbsp;İstifadəçi Servisə özü haqqında şəxsi məlumatların və istənilən başqa informasiyanın verilməsi haqqında sərbəst və könüllü qərar qəbul edir, həmçinin də bununla belə şəxsi məlumatların və informasiyanın Administrasiya tərəfindən işlənməsinə, işlənməsi üçün onların Administrasiyanın tapşırığı ilə hərəkət edən başqa İstifadəçilərə və/və ya üçüncü şəxslərə ötürülməsinə öz razılığını bildirir.</p>
            <p><strong>1.7.</strong>&nbsp;Şəxsi məlumatların işlənməsi istənilən hərəkət və ya hərəkətlərin toplanma, qeydiyyat, yığım, saxlama, uyğunlaşma, dəyişiklik, yeniləmə, istifadə və yayılma kimi məcmusudur (yayılma, reallaşdırma, ötürülmə, həmçinin xaricə) və şəxsi məlumatların, həmçinin informasiya (avtomatlaşdırılmış) sistemlərinin istifadəsi ilə məhv edilməsidir.</p>
            <p><strong>1.8.</strong>&nbsp;Şəxsi məlumatların işlənməsinin məqsədləri, o cümlədən, aşağıdakılardır:</p>
            <p><strong>1.8.1.</strong>&nbsp;Servisin, onun servislərinin və xidmətlərinin fəaliyyətinin yaxşılaşması üçün statistik və analitik məlumatların alınması;</p>
            <p><strong>1.8.2.</strong>&nbsp;göstərilən xidmətlərin spektrinin genişləndirilməsi;</p>
            <p><strong>1.8.3.</strong>&nbsp;Servisin və ya üçüncü şəxslərin informasiya və ya reklam xəbərlərinin alınması (yeni imkanlar, aksiyalar və başqa xəbərlər haqqında xəbərdarlıq);</p>
            <p><strong>1.8.4.</strong>&nbsp;İstifadəçilərin və ya üçüncü şəxslərin qanunsuz və ya icazəsiz hərəkətlərinin xəbərdarlığı və qabağının alınması;</p>
            <p><strong>1.8.5.</strong>&nbsp;qüvvədə olan qanunvericiliyin tələblərinə riayətin təminatı.</p>
            <p><strong>1.9.</strong>&nbsp;Servis İstifadəçilər haqqında növbəti informasiyanı toplayır:</p>
            <p><strong>1.9.1.</strong>&nbsp;Servisdən istifadə zamanı Administrasiyaya İstifadəçinin daxil etdiyi şəxsi informasiyanı göstərir və ya başqa üsulla açır. Belə informasiya, xüsusi halda (lakin, məhdudlaşdırılmadan), İstifadəçinin adı və soyadı, elektron poçt ünvanı və parolu, telefon nömrəsi, İstifadəçinin yerləşdiyi yer, həmçinin ünvanı ola bilər. Əgər İstifadəçi sosial şəbəkənin profili vasitəsilə daxil olursa, Servis həmçinin belə sosial şəbəkənin profilində yerləşdirilmiş informasiyanı toplaya bilər. İstifadəçi ona verilmiş informasiyaya görə məsuliyyət daşıyır, halbuki Servis İnternetdə İstifadəçinin məlumatlarının yayılması və dərc edilməsi üçün kanalı verir.</p>
            <p><strong>1.9.2.</strong>&nbsp;Servisin, ona giriş zamanı, proqram təminatı tərəfindən avtomatik toplanan texniki informasiya.</p>
            <p><strong>1.10.</strong>&nbsp;Servis, həmçinin də Administrasiya, irqi və ya etnik mənşə haqqında məlumatları, siyasi, dini və dünyagörüşü məsləklər, siyasi partiyalara və həmkarlar ittifaqlarına üzvlük, cinayət cəzasına məhkumluqlar, həmçinin də sağlamlığa, cinsiyyət həyatına aid olan məlumatları, biometrik və ya genetik məlumatları toplamır və işləmir.</p>
            <p><strong>1.11.</strong>&nbsp;Servis və Administrasiya Servisə aidiyyəti olmayan üçüncü şəxslərə İstifadəçilər tərəfindən təqdim edilmiş heç bir şəxsi və ya başqa məlumatları, İstifadəçinin belə icazəni verdiyi hal istisna olmaqla, həmçinin də İstifadəçi razılaşması ilə və ya qanunvericiliklə nəzərdə tutulmuş hallarda, vermir.</p>
            <p><strong>1.12.</strong>&nbsp;Servis və Administrasiya bəzi hallarda bəzi məlumatları Servislə əməkdaşlıq edən və ya Administrasiya ilə bağlı olan şəxslərə verə bilər.</p>
            <p><strong>1.13.</strong>&nbsp;Administrasiya Servisdən istifadə prosesində İstifadəçilər tərəfindən verilmiş informasiyanı və şəxsi məlumatları satmır və icarəyə vermir.</p>
            <p><strong>1.14.</strong>&nbsp;İstifadəçilər arasında qarşılıqlı təsiri yüngülləşdirmək üçün, xidmətlər başqa İstifadəçilərin əlaqə informasiyasına məhdudlaşdırılmış girişi nəzərdə tutur. Başqa İstifadəçilər tərəfindən verilmiş məlumatlardan istifadə hüququ İstifadəçi razılaşması ilə məhdudlaşdırılır.</p>
            <p><strong>1.15.</strong>&nbsp;Servisin İstifadəçisi başqa İstifadəçi tərəfindən verilmiş məlumatlardan, belə İstifadəçinin yazılı icazəsi olmadan və ya belə məlumatlardan hər hansı başqa yolla istifadə etmək hüququnun təsdiqi olmadan istifadə etməməyi öhdəsinə götürür. Servisdən istifadə ilə əlaqədar başqa İstifadəçilər haqqında İstifadəçi tərəfindən alınmış bütün məlumatlar yalnız Mallar barəsində sazişlərin icrasında istifadə edilə bilər. Beləliklə, İstifadəçiyə düz reklam göndərməsi və ya arzu edilməyən elektron xəbərlərin başqa göndərməsi məqsədləri üçün elektron ünvandan istifadə etməyə, başqa İstifadəçinin telefon nömrəsi kimi, həmçinin xəbərsiz edilən qeyri-qanuni hərəkətlərə və ya başqa İstifadəçinin xəbəri və razılığı olmadan həyata keçirilmiş hərəkətlərə icazə verilmir.</p>
            <p><strong>1.16.</strong>&nbsp;Servisin İstifadəçisi onun Servisdən istifadə prosesində verdiyi şəxsi və başqa məlumatları istənilən qismən vaxt dəyişdirmək, silmək və ya başqa üsulla redaktə etmək imkanına malikdir.</p>
            <p><strong>1.17.</strong>&nbsp;İstifadəçi onun göstərdiyi istənilən informasiyanın və məlumatların dəqiqliyi və düzgünlüyü üçün məsuliyyət daşıyır.</p>
            <p><strong>1.18.</strong>&nbsp;Əgər İstifadəçi girişi, qeydiyyatı həyata keçirmişsə və OpenID xidmətinin köməyi ilə Servisdən istifadə edirsə, İstifadəçi onun məlumatlarının ötürülməsi və onlardan istifadə qaydasını belə xidmətin parametrlərində qura bilər.</p>
            <p><strong>1.19.</strong>&nbsp;Servis və Administrasiya İstifadəçinin şəxsi məlumatlarının üçüncü şəxslərin icazəsiz girişindən müdafiəsi üçün bütün səmərəli ölçüləri qəbul edir.</p>
            <p><strong>1.20.</strong>&nbsp;Servis tərəfindən toplanmış və işlənmiş bütün şəxsi məlumatlar bir və ya bir neçə qorunan korporativ şəbəkədən kənarda giriş olmayan serverdə saxlanılır. Administrasiyanın İstifadəçilərin şəxsi və başqa informasiyasından girişlə və istifadə ilə funksiyaları yerinə yetirən bütün əməkdaşları üçüncü şəxslərə İstifadəçilər haqqında informasiyanın yayılmaması haqqında razılaşma imzalamışlar.</p>
            <p><strong>2. Cookies, veb-mayaklar, və oxşar texnologiyalar</strong></p>
            <p><strong>2.1.</strong>&nbsp;Servis informasiyanın saxlanılması üçün cookies fayllarından, veb-mayaklardan və başqa oxşar texnologiyalardan istifadə edə bilər. Bu fayllar veb-saytın və onun əlavələrinin istifadəsini yüngülləşdirmək məqsədi ilə, Servis xidmətlərinin keyfiyyətinin artırılması məqsədi ilə (həmçinin təhlükəsizlik), həmçinin reklam məqsədi ilə istifadə olunur.</p>
            <p><strong>2.2.</strong>&nbsp;Servis tərəfindən İstifadəçidən alınan istənilən informasiya, həmçinin cookies fayllarının İstifadəçinin brauzerində yerləşdirilməsi, xəbərdarlıq vasitəsilə və İstifadəçinin icazəsi ilə həyata keçirilir. Servisdən istifadəni davam edərək, İstifadəçi Servisə cookies fayllarının İstifadəçinin brauzerində saxlamasına öz icazəsini verir.</p>
            <p><strong>2.3.</strong>&nbsp;Servis cookies-dən və oxşar texnologiyalardan, İstifadəçinin brauzerinin fəallığı prosesində İstifadəçinin qurğusunda qalan və cookies, həmçinin də daha uzun müddətli dövr ərzində İstifadəçinin qurğusunda qalan başqa oxşar texnologiyalardan istifadə edir. İstifadəçi belə cookies və oxşar texnologiyaları bloklamaqda, silməkdə və ya kəsməkdə, əgər İstifadəçinin qurğusu buna icazə verirsə, haqlıdır.</p>
            <p><strong>2.3.1.</strong>&nbsp;Cookies – kompüter terminologiyasında Servisdən alınmış mətn və ya ikili məlumatlar şəklində informasiyanın təsviri üçün istifadə edilən anlayışdır ki, İstifadəçidə saxlanılır, yəni brauzerdə, sonra isə, əgər Servisin İstifadəçisi ona təkrar olaraq baş çəkirsə, Servisə yollanır. Beləliklə, Servis baş çəkmə vaxtı İstifadəçinin brauzerini qeyd edir. Cookies faylları sistemə giriş və statistika yığımı üçün lazımı məlumatları yazaraq Servisdən istifadəni yüngülləşdirir. Cookies falları özündə şəxsi məlumatları saxlamır.</p>
            <p><strong>2.3.2.</strong>&nbsp;Veb-mayaklar – Servisdə, həmçinin onun xidmətlərində, əlavələrdə, mübadilə xəbərlərində, və İstifadəçini müəyyən etmək üçün adətən cookies ilə uyğunluqda işləyən alətlərdə qoşula bilən kiçik qrafik təsvirlərdir (həmçinin "nöqtə markörləri" və ya "Şəbəkə mayakları" kimi məlumdur).</p>
            <p><strong>2.3.3.</strong>&nbsp;Oxşar texnologiyalar – lokal ümumi obyektləri və ya lokal anbarı və proqram veb-əlavələrinin başqa metodları istifadə edən, brauzerdə və ya qurğuda informasiyanı saxlayan, "flashcookies" "HTML 5 cookies" kimi, texnologiyalardır. Bu texnologiyalar İstifadəçinin bütün brauzerlərində işləyə bilər, bəzi hallarda isə tamamilə brauzerlə idarə oluna bilmirlər və İstifadəçi tərəfindən təyin edilmiş əlavələr və ya qurğular vasitəsilə bilavasitə idarəetməni tələb edə bilərlər.</p>
            <p><strong>2.4.</strong>&nbsp;Cookies-ə və oxşar texnologiyalara icazə olunmamış girişin qarşısını almaq üçün Administrasiya bütün təhlükəsizlik tədbirlərini görür. İstifadəçi analoji təhlükəsizlik tədbirlərini görməyi öhdəsinə götürür. Administrasiya zəmanət verir ki, yalnız Administrasiya və/və ya Servis xidmətlərinin səlahiyyətli təchizatçıları cookies məlumatlarına girişə malikdirlər.</p>
            <p><strong>2.5.</strong>&nbsp;Servisin xidmətlərinin təchizatçıları Servisin müxtəlif aspektləri ilə kömək edən şirkətlərdir. Administrasiya Servisin uyğun olan xidmətlərinin İstifadəçiyə verilməsi, həmçinin də Servisin bilavasitə fəaliyyəti ilə bağlı başqa məqsədlər üçün xidmətlərin bəzi səlahiyyətli təchizatçılarından istifadə edir. Xidmətlərin belə təchizatçıları həmçinin Servisin (kənar cookies) xidmətləri vasitəsilə cookies-i İstifadəçinin qurğusunda yerləşdirə bilərlər. Onlar həmçinin başqa informasiyanı, məsələn, IP-ünvan və ya başqa eyniləşdiriciləri, toplaya bilərlər.</p>
            <p><strong>2.6.</strong>&nbsp;Servisin yuxarıda göstərilmiş texnologiyalardan istifadə vasitəsilə toplayıb və saxladığı istənilən informasiyadan İstifadəçinin icazəsi ilə istifadə olunur.</p>
            <p><strong>2.7.</strong>&nbsp;İstifadəçi brauzerin və ya qurğunun parametrlərində cookies-i idarə edə bilər. İnformasiyanın toplanmasından və saxlanılmasından imtina üçün brauzerin parametrlərində "Cookies-i saxlamamaq" bəndində bayraqcığı qurmaq, həmçinin "Cookies-i təmizləmək" düyməsini basmaq lazımdır.</p>
            <p><strong>2.8.</strong>&nbsp;Sistemdə olan texniki xarakterli informasiya, məsələn, ip-ünvanlar, Servis tərəfindən şəbəkə avadanlığının xidməti üçün, həmçinin statistik və başqa informasiyanın ümumiləşdirilməsi üçün istifadə olunur.</p>
            <p><strong>2.9.</strong>&nbsp;İstifadəçinin fərdi ehtiyaclarına və maraqlarına uyğunlaşdırılan verilən servislərin yüksək keyfiyyətli təminatı məqsədi ilə Servis İstifadəçinin sistemə son girişinin məlumatlarını saxlayır.</p>
            <p><strong>3. Məxfiliyin siyasətinə dəyişikliklərin daxil etməsi</strong></p>
            <p><strong>3.1.</strong>&nbsp;Administrasiya Məxfilik Siyasətinə dəyişikliklər edə, silə və ya qaydalarını yeniləyə bilər.</p>
            <p><strong>3.2.</strong>&nbsp;Əgər İstifadəçi daxil edilmiş dəyişikliklərlə razı deyilsə, o Servisdən istifadəni dayandırmalıdır. Əgər İstifadəçi Servisdən istifadə etməyə davam edirsə, o razılaşır və bütün dəyişiklikləri və Məxfilik siyasətinin yeni redaksiyasını bütövlükdə qəbul edir.</p>
            <p>&nbsp;</p>
         </div>
      </div>
   </div>
</main>